/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Employee.Payroll;

import org.junit.Test;
import static org.junit.Assert.*;

public class EmployeePayrollServiceTest {
    
}
